### ISSUE TITLE
Conjunto y relaciones 

### ISSUE THREAD

**Issue by Nelson295281** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Nelson295281#2]
[Conjuntos y Relaciones. Nelson Macario Martínez Hernández.pdf](https://github.com/user-attachments/files/17091767/Conjuntos.y.Relaciones.Nelson.Macario.Martinez.Hernandez.pdf)

**Comment by Evelyn-sj13** [comment]
Exposición de Ideas Centrales:5/5
Redacción y Ortografía:5/5
Presentación visual:4/5
Referencias:5/5
Calificación Final:19/20

**Comment by josealfredo79** [comment]
bien hecho y revisado..
